7800.main: Migrated data from d7
faust174/migration pull request #1
Opened 2024-04-12 09:22 UTC by faust174

2024-04-12 09:34 UTC, KuzyaWkk requested changes
Add comment to function transform

2024-04-12 09:34 UTC, KuzyaWkk commented on web/modules/custom/migration/src/Plugin/migrate/process/CustomLinkPlugin.php
> +  public function transform($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property) {
Missed comment

2024-04-12 09:34 UTC, KuzyaWkk commented on web/modules/custom/migration/src/Plugin/migrate/process/CustomLinkPlugin.php
I'm not sure this is the right way to do things

2024-04-12 09:46 UTC, KuzyaWkk approved these changes

2024-04-15 06:42 UTC, lavrenchuk-dev requested changes

2024-04-15 06:42 UTC, lavrenchuk-dev commented on web/modules/custom/migration/src/Plugin/migrate/process/CustomLinkPlugin.php
> +    return preg_replace_callback($pattern, $callback, $value);
There are libraries / helpers to work with the HTML
regex magic is not needed (not explicitly at least)

2024-04-15 08:01 UTC, faust174 commented on web/modules/custom/migration/src/Plugin/migrate/process/CustomLinkPlugin.php
> +        $is_valid = \Drupal::pathValidator()->isValid($href);
Didn't use DI here cause faced an error, was not able to fix it fast and didn't want to spend too much time fixing it. So left it as it is.

Error message: TypeError: Drupal\migration\Plugin\migrate\process\CustomLinkPlugin::__construct(): Argument #4 ($pathValidator) must be of type Drupal\Core\Path\PathValidatorInterface, Drupal\node\Plugin\migrate\D7NodeTranslation given

2024-04-15 12:33 UTC, lavrenchuk-dev approved these changes

2024-04-15 12:34 UTC, lavrenchuk-dev commented
@faust174 I have no rights to merge PRs here
Feel free to merge yourself

2024-04-15 12:51 UTC, merged